### ISSUE TITLE
Declare file extension support

### ISSUE THREAD

**Issue by SeanLeRoy** [bioio-devs/cookiecutter-bioio-reader#2]
### Feature Description

Either in the cookiecutter or somewhere visible we'll need to make sure that plug-ins specify which file formats they support. Specifically they will need to mention which file extensions they are intended to support (should wildcards be allowed like for bioformats?).

**Comment by evamaxfield** [comment]
Work in progress version of that here: https://github.com/bioio-devs/cookiecutter-bioio-reader/blob/main/{{%20cookiecutter.project_slug%20}}/{{%20cookiecutter.python_slug%20}}/reader_metadata.py

**Comment by SeanLeRoy** [comment]
Ah that should work for what I was thinking with this issue
