### ISSUE TITLE
cookiecutter notes

### ISSUE THREAD

**Issue by SeanLeRoy** [bioio-devs/cookiecutter-bioio-reader#5]
* remove `data_dir` fixture, possibly delete conftest altogether
* remove python 3.8 support
* add python 3.11 support?

**Comment by evamaxfield** [comment]
Agree! I would also maybe consider some possible mechanism for testing upstream bioio-base compatibility.

Like how we are doing a test-upstreams on aicsimageio but the downstream plugins should have tests for upstream with bioio-base

**Comment by evamaxfield** [comment]
Can be future thing tho
